---
title: Consultation (template)
subtitle: Descriptive plots
author: Data Science Hub
date: "`r Sys.Date()`"
output: 
  pdf_document: 
    latex_engine: pdflatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(
  "tidyverse",
  "yaml",
  "tidytext"
)

config <- yaml::read_yaml("../input/config.yml")
general_params <- config$general_params

lda_object <- readRDS("../output/lda_object.rds")

questions_text <- names(lda_object)[i]

beta <- lda_object[[questions_text]][["beta"]]
gamma <- lda_object[[questions_text]][["gamma"]]
```

## Question: `r question_text`

## Most important words by topics

```{r, fig.width = 12, fig.height = 12, warning=FALSE, echo=FALSE, message=FALSE, results=FALSE} 
plot <- beta %>% 
  group_by(topic) %>% 
  arrange(-beta) %>% 
  slice_head(n = 10) %>% 
  ungroup() %>% 
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term)) + 
  geom_bar(stat = "identity", fill = "#006652", alpha = 0.65) + 
  scale_y_reordered() +
  facet_wrap(~ topic, scales = "free", ncol = 4) + 
  theme_minimal(base_size = 18)

print(plot)
```

## Topics per response

``` {r, fig.width = 12, fig.height = 7, warning=FALSE, echo=FALSE, message=FALSE}

# Calculate gamma threshold to leave all responses with at least one topic.
gamma_threshold <- gamma %>%
  summarise(max_gamma = max(gamma), .by = document) %>%
  slice_min(max_gamma, n = 1) %>%
  pull(max_gamma) %>%
  max()

# Filter out topic-document assignments with gamma lower than threshold
gamma_filtered <- gamma %>% 
  filter(gamma >= gamma_threshold) %>% 
  count(document) %>% 
  mutate(n = ifelse(n > 15, 15, n)) %>% 
  group_by(n) %>% 
  summarise(count = sum(n))

plot <- gamma_filtered %>% 
  ggplot(aes(n, count)) +
  geom_col(fill = "#006652", alpha = 0.65) +
  scale_y_continuous(expand = c(0, 0)) + 
  theme_minimal(base_size = 18) +
  theme() + 
  labs(
    title = "Topics per response",
    x = "Number of topics",
    y = "Number of responses"
  )

print(plot)
```

## Indicative text (Top 5 by topic)

``` {r, warning=FALSE, echo=FALSE, message=FALSE, results="asis"}
# Define the current question text
question_text <- question_text_list[i]

# Filter for responses to said question only
responses <- responses_all %>% 
  select(response_id, all_of(question_text)) %>% 
  na.omit()

# Get total number of topics to loop through
no_topics <- gamma %>% pull(topic) %>% max()

# Function to get top 5 response text for a given topic
get_topic_text <- function(topic_num){
  # Filter and sort gamma values for the given topic
  gammas <- gamma %>%
    filter(topic == topic_num) %>%
    arrange(desc(gamma))
  
  # Get top 5 gamma values
  top_five_gammas <- gammas %>% 
    slice_head(n = 5) %>%
    mutate(document = as.integer(document))
  
  # Load corresponding answers
  answers <- read_csv(
    paste0("../output/output_for_labellers/topic_gamma_q", question_number, ".csv")
  )
  
  # Join with responses to get the full text
  top_gamma_answers <- top_five_gammas %>% 
    left_join(responses, by = c("document" = "response_id")) %>% 
    select(response_text = all_of(question_text))
  
  # Clean and return the text
  values_list <- top_gamma_answers$response_text %>% 
    str_replace_all("[^[:punct:][:alnum:]\\s]", "")
  
  return(values_list)
}

# Loop through each topic and print the results
for (topic_num in 1:no_topics){
  cat("\n## Topic ", topic_num, "\n")
  
  # Plot the top 10 words for the topic
  betas <- beta %>%
    filter(topic == topic_num) %>%
    arrange(desc(beta))
  
  top_ten_betas <- betas %>%
    slice_head(n = 10)
  
  plot <- top_ten_betas %>%
    ggplot(aes(beta, reorder(term, beta))) +
    geom_bar(stat = "identity", fill = "blue", alpha = 0.75) +
    labs(
      title = sprintf("Most important words", topic_num),
      x = "Beta",
      y = ""
    ) +
    theme_minimal(base_size = 14)
  
  print(plot)
  
  cat("\n\n")
  
  # Fetch and print the top 5 texts for the topic
  topic_texts <- get_topic_text(topic_num)
  
  for (u in seq_along(topic_texts)) {
    cat("\n### ", as.character(u), "\n")
    cat(topic_texts[u], "\n")
  }
}

```
